name: Deploy website
permissions:
  contents: write
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install --legacy-peer-deps
      - name: build
        run: npm run build
      - name: rename
        run: mv build qc
      - name: get redirect
        run: mv public/redirect.html index.html
      - name: package
        run: tar -czf build.tar.gz qc index.html
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build.tar.gz
